"""
Stepper axis driver for the Laser Turret board.

Step pulses are generated by an RP2040 PIO state machine, one per axis
(pan on PIO0, tilt on PIO1), so pulse timing is hardware-exact and immune
to MicroPython's garbage collector.  The CPU only feeds a per-step delay
word into the TX FIFO; the FIFO provides the buffering that lets a
trapezoidal acceleration profile stream out smoothly.

Supports both A4988 and DRV8825 carriers -- the microstep truth tables
differ and picking the wrong one silently changes your step count.
"""

import gc
import time

import machine
import rp2
from machine import Pin, Timer

import config
import pinmap

# --------------------------------------------------------------------------
# Microstep truth tables.  (m0, m1, m2) -> divisor.
#
# These are NOT the same chip to chip.  Note 1/16 in particular:
#   A4988   1/16 = MS1,MS2,MS3 = 1,1,1
#   DRV8825 1/16 = M0,M1,M2    = 0,0,1
# Wiring them from the wrong table is a classic source of "my motor turns
# exactly half as far as I asked".
# --------------------------------------------------------------------------
MICROSTEP_TABLE = {
    "A4988": {
        1:  (0, 0, 0),
        2:  (1, 0, 0),
        4:  (0, 1, 0),
        8:  (1, 1, 0),
        16: (1, 1, 1),
    },
    "DRV8825": {
        1:  (0, 0, 0),
        2:  (1, 0, 0),
        4:  (0, 1, 0),
        8:  (1, 1, 0),
        16: (0, 0, 1),
        32: (1, 0, 1),
    },
}

# PIO program overhead, in state-machine cycles, per step.  Derived from the
# instruction count below: out=1, set hi=1+7 delay, set lo=1, loop=x+1.
_PIO_OVERHEAD_CYCLES = 11

# Moves shorter than this skip the pre-move gc.collect().  Measured on a Pico
# at 125 MHz: collect() is ~1.7 ms, and total fixed overhead per move() is
# ~3.5 ms, so collecting before a 10-step move costs more than the move.
_GC_THRESHOLD_STEPS = 256


@rp2.asm_pio(set_init=rp2.PIO.OUT_LOW, autopull=True, pull_thresh=32)
def _step_program():
    """One FIFO word per step; the word is the extra delay in PIO cycles."""
    wrap_target()
    out(x, 32)              # fetch this step's delay
    set(pins, 1)      [7]   # STEP high for 8 cycles (A4988 needs >=1 us)
    set(pins, 0)            # STEP low
    label("hold")
    jmp(x_dec, "hold")      # burn x+1 cycles to set the period
    wrap()


@rp2.asm_pio(set_init=rp2.PIO.OUT_LOW)
def _vel_program():
    """
    Free-running step generator: one FIFO word sets the PERIOD, and it sticks.

    The move program takes one word per step, which is right for a move of
    known length and useless for tracking -- the CPU would have to feed it
    forever. Here the period lives in X and survives, so the state machine
    keeps stepping at the last commanded rate with no CPU involvement at all.

    The trick is `pull(noblock)`: on an empty FIFO it copies X into OSR
    (RP2040 datasheet 3.4.7) rather than stalling, so `mov(x, osr)` just puts
    the same period back. Write a new word and the next iteration picks it up.

    Cycles per step = 15 + Y, so period = clock / rate and Y = period - 15.
    A period of 0 means idle: no pulses, but the machine keeps polling, so it
    resumes the instant a rate arrives.
    """
    label("top")
    pull(noblock)            # empty FIFO -> OSR = X, so the period persists
    mov(x, osr)
    jmp(not_x, "top")        # 0 == idle
    mov(y, x)                # Y is the countdown; X must survive it
    set(pins, 1)    [7]      # STEP high 8 cycles (A4988 needs >= 1 us)
    set(pins, 0)
    label("hold")
    jmp(y_dec, "hold")
    jmp("top")


# The two instructions the velocity loop executes from the CPU side, encoded
# ONCE at import.
#
# sm.exec("pull(noblock)") looks harmless and is not: it assembles that string
# on every single call. At 200 Hz x 2 axes that is 400 parses a second inside
# an interrupt handler, where MicroPython cannot run the allocator at all.
# Encoding to an int up front makes the ISR path a plain register write.
try:
    _VEL_PULL = rp2.asm_pio_encode("pull(noblock)", 0)
    _VEL_MOV_X_OSR = rp2.asm_pio_encode("mov(x, osr)", 0)
    _VEL_SET_LOW = rp2.asm_pio_encode("set(pins, 0)", 0)
except (AttributeError, NotImplementedError):
    # Host-side fakes do not implement the encoder; the strings are only ever
    # used off-board, where allocation is fine.
    _VEL_PULL = "pull(noblock)"
    _VEL_MOV_X_OSR = "mov(x, osr)"
    _VEL_SET_LOW = "set(pins, 0)"


class StepperError(Exception):
    """A real fault: the hardware is in a state that cannot be driven."""
    usage = False


class StepperUsageError(StepperError):
    """
    A bad argument, not a hardware fault.

    Callers distinguish it by the `usage` flag rather than by catching a
    second base class: MicroPython cannot build an exception from two
    built-in bases with different instance layouts, so the obvious
    `(StepperError, ValueError)` raises "multiple bases have instance
    lay-out conflict" at import time on the Pico even though CPython
    accepts it.

    The CLI keys off this flag to avoid de-energising the motors just
    because someone typed an unsupported microstep ratio -- on a tilt axis
    with gravity on it, dropping holding torque over a typo drops the barrel.
    """
    usage = True


class Axis:
    """One stepper axis: driver control pins plus a PIO step generator."""

    def __init__(self, spec, sm_id):
        self.spec = spec
        self.name = spec["name"]
        self.ref = spec["ref"]

        self.step_pin = Pin(spec["step"], Pin.OUT, value=0)
        self.dir_pin = Pin(spec["dir"], Pin.OUT, value=0)
        # Driver EN is active LOW.  Start HIGH == disabled == coils released.
        self.en_pin = Pin(spec["en"], Pin.OUT, value=1)
        self.m_pins = (
            Pin(spec["m0"], Pin.OUT, value=0),
            Pin(spec["m1"], Pin.OUT, value=0),
            Pin(spec["m2"], Pin.OUT, value=0),
        )

        self._init_pad2(spec["fault"])

        self.position = 0          # in microsteps, signed
        self.microstep = 1
        self._enabled = False
        self._abort = False
        self._last_move = {}

        self.sm_id = sm_id
        self.sm = rp2.StateMachine(
            sm_id,
            _step_program,
            freq=config.PIO_CLOCK_HZ,
            set_base=self.step_pin,
        )

        # Velocity mode runs on a SECOND state machine sharing the same STEP
        # pin. Two machines rather than one reprogrammed machine because
        # swapping a PIO program at runtime means re-uploading instructions
        # and re-deriving the pin mapping every time the mode changes; keeping
        # both resident costs two SMs and makes mode switching a pair of
        # active() calls that cannot half-fail.
        self.mode = "idle"                 # "idle" | "move" | "vel"
        self.vel_sm_id = sm_id + config.VEL_SM_OFFSET
        self.vel_sm = rp2.StateMachine(
            self.vel_sm_id,
            _vel_program,
            freq=config.VEL_PIO_CLOCK_HZ,
            set_base=self.step_pin,
        )
        self.vel_sm.active(0)
        self.target_rate = 0               # signed microsteps/s, INT
        self.current_rate = 0              # signed, after accel limiting, INT
        # DIRECTION CACHE FOR VELOCITY MODE. vel_tick() writes the DIR pin only
        # when the sign it wants differs from this, so this MUST always equal
        # what the pin physically says, or a motor runs the wrong way and
        # nothing reports it. It used to start at 1 (forward) while dir_pin
        # above is created at 0 (reverse), and position moves updated the pin
        # without updating this -- so after homing, whose last coordinated
        # move leaves motor A's pin at reverse, the first positive `vel` on A
        # was judged "already forward" and A ran BACKWARDS until the loop
        # happened to ask for a negative rate. Measured 2026-09-20 on
        # run_124411 (image Jacobian column A inverted, gyro per-motor sign
        # flipped) and run_122343. 0 means UNKNOWN: the first non-zero rate
        # always writes DIR. Every pin write below keeps this in step.
        self._vel_dir = 0
        self._pos_micro = 0                # microsteps * 1e6, dead reckoned
        # Translator phase, in 1/16-step units x 1e6, NEVER reset.
        #
        # The A4988 datasheet requires a step-mode change to happen "at a step
        # position that is common to both step modes", otherwise the internal
        # translator lands on a different state and a step is silently lost.
        # That has to be judged against the DRIVER's phase, which only
        # power-on or reset returns to home -- not against `position`, which
        # `zero`/`dzero` moves to wherever the operator happens to be. Testing
        # a re-zeroable counter makes the alignment check agree with itself
        # and disagree with the hardware.
        self._phase_micro = 0
        self._phase_mult = 1               # 1/16-steps per step at this mode
        # Precomputed so the timer callback never does a dict lookup or a
        # multiply it can avoid -- see vel_tick on why it must not allocate.
        self._invert_dir = bool(config.INVERT_DIR.get(self.name, False))
        self._accel_per_tick = int(getattr(config, "VEL_ACCEL",
                                           config.ACCEL.get(self.name, 20000))
                                   * config.VEL_TICK_MS / 1000)
        if self._accel_per_tick < 1:
            self._accel_per_tick = 1
        self._vel_clock = int(config.VEL_PIO_CLOCK_HZ)
        # Creating the StateMachine switched the STEP pad's function to PIO.
        # Hand it straight back to SIO so the line is a defined, driven LOW
        # while idle -- a floating STEP input can pick up stray pulses.
        self._release_step_pin()

        self.set_microstep(config.DEFAULT_MICROSTEP.get(self.name, 1))

    # ------------------------------------------------------------------
    # STEP pad ownership.  MicroPython sets the pad's FUNCSEL to PIO once,
    # at StateMachine construction.  Nothing re-applies it on sm.active(1),
    # so if we ever hand the pad back to SIO (for single_step, or to park it
    # low) we must explicitly re-claim it before the next PIO move.
    # ------------------------------------------------------------------
    def _claim_step_pin(self):
        funcsel = _FUNCSEL_PIO0 if self.sm_id < 4 else _FUNCSEL_PIO1
        _set_funcsel(self.spec["step"], funcsel)

    def _release_step_pin(self):
        _set_funcsel(self.spec["step"], _FUNCSEL_SIO)
        self.step_pin.init(Pin.OUT)
        self.step_pin.value(0)

    # ------------------------------------------------------------------
    # Driver pad 2 -- nFAULT on a DRV8825, VDD on an A4988 (Finding #2)
    # ------------------------------------------------------------------
    def _init_pad2(self, gpio):
        self.pad2_gpio = gpio
        self.pad2_mode = None
        self.fault_pin = None

        if config.DRIVER_TYPE == "DRV8825":
            # Open-drain, active low.  Pull up so an un-asserted fault reads 1.
            self.fault_pin = Pin(gpio, Pin.IN, Pin.PULL_UP)
            self.pad2_mode = "fault-in"
            return

        src = config.A4988_VDD_SOURCE
        if src == "gpio":
            # Drive it as the chip's logic supply.  Crank the pad's drive
            # strength to 12 mA first so the 3.3 V does not sag under the
            # A4988's VDD draw (~5 mA typ, 10 mA max).
            _set_drive_strength(gpio, 3)
            self.vdd_pin = Pin(gpio, Pin.OUT, value=1)
            self.pad2_mode = "vdd-from-gpio"
            # Let VDD come up and the chip's power-on reset finish before
            # anything drives EN or STEP.  Charging the carrier's 0.1 uF
            # decoupling cap at 12 mA takes ~30 us; the chip's internal POR
            # needs longer, so give it a few milliseconds.
            time.sleep_ms(5)
        elif src == "external":
            # Bodged to 3V3.  Never drive it -- that would be a supply short.
            Pin(gpio, Pin.IN, None)
            self.pad2_mode = "vdd-external"
        else:
            Pin(gpio, Pin.IN, None)
            self.pad2_mode = "off"

    def fault(self):
        """True if the driver is reporting a fault.  None if not observable."""
        if self.fault_pin is None:
            return None
        return self.fault_pin.value() == 0

    # ------------------------------------------------------------------
    # Enable / microstepping
    # ------------------------------------------------------------------
    def enable(self):
        if config.DRIVER_TYPE == "A4988" and self.pad2_mode == "off":
            raise StepperError(
                "%s: A4988 has no logic supply (A4988_VDD_SOURCE='off'). "
                "See HARDWARE_NOTES.md Finding #2." % self.name)
        self.en_pin.value(0)
        self._enabled = True

    def disable(self):
        self.en_pin.value(1)
        self._enabled = False

    @property
    def enabled(self):
        return self._enabled

    def set_microstep(self, div):
        table = MICROSTEP_TABLE[config.DRIVER_TYPE]
        if div not in table:
            raise StepperUsageError(
                "%s does not support 1/%d microstepping (have: %s)"
                % (config.DRIVER_TYPE, div, sorted(table)))
        bits = table[div]
        old_div = self.microstep
        for pin, bit in zip(self.m_pins, bits):
            pin.value(bit)
        self.microstep = div
        self._phase_mult = 16 // div if div <= 16 else 1
        # Rescale the step counters. A microstep change alters what a count
        # MEANS -- 1600 counts is a full turn at 1/8 and half a turn at 1/16 --
        # so leaving them alone silently doubles or halves every angle the
        # firmware reports. This was a latent bug for as long as microstepping
        # was only ever set once at boot; dynamic switching makes it live.
        if old_div and div != old_div:
            self.position = self.position * div // old_div
            self._pos_micro = self._pos_micro * div // old_div
            # Rate is in steps/s, and a step is now a different size, so the
            # same ANGULAR speed needs a proportionally different step rate.
            self.target_rate = self.target_rate * div // old_div
            self.current_rate = self.current_rate * div // old_div
            self._accel_per_tick = max(
                1, int(getattr(config, "VEL_ACCEL",
                               config.ACCEL.get(self.name, 20000))
                       * config.VEL_TICK_MS / 1000) * div // 16)
        # The A4988 needs a moment after a mode change before the next step.
        time.sleep_us(50)
        return bits

    # ------------------------------------------------------------------
    # Velocity mode
    # ------------------------------------------------------------------
    def _period_for(self, rate):
        """PIO Y value for |rate| microsteps/s. 0 means idle."""
        if rate <= 0:
            return 0
        period = int(config.VEL_PIO_CLOCK_HZ / rate)
        y = period - config.VEL_CYCLE_OVERHEAD
        return y if y > 0 else 1

    def _set_period(self, y):
        """
        Push a new period and make it take effect on the NEXT step.

        Not just sm.put(): at a few hundred steps/s the 4-deep TX FIFO fills
        with periods the loop wrote on earlier ticks, and the rate the motor
        actually runs lags the commanded one by up to four steps -- which in a
        tracking loop reads as sloppy, laggy following that no amount of gain
        tuning fixes.

        So: write the word, then immediately pull it into OSR and copy it to X
        from the CPU side. The FIFO is left empty every time, and X is only
        read at the top of a step, so clobbering it mid-hold-loop is harmless.
        """
        sm = self.vel_sm
        sm.put(y)
        sm.exec(_VEL_PULL)
        sm.exec(_VEL_MOV_X_OSR)

    def enter_vel_mode(self):
        if self.mode == "vel":
            # ALREADY IN VELOCITY MODE -- but re-claim the STEP pad anyway.
            #
            # coordinated_move() has no velocity-mode guard (move() and
            # single_step() both do), and its finally clause calls
            # _release_step_pin() on BOTH axes, which hands the pad back to
            # SIO. Returning early here meant the pad was never re-claimed:
            # vel_tick went on writing periods and integrating _pos_micro
            # while not one pulse reached the driver. That is a motor whose
            # counter advances and whose shaft does not move, until reboot --
            # measured on the bench 2026-09-20, tilt only, after a
            # position-mode move on tilt.
            #
            # Claiming an already-claimed pad is a single register write and
            # is harmless, so do it unconditionally rather than trying to
            # guess whether something took it.
            self._claim_step_pin_vel()
            return
        if self.mode == "move":
            raise StepperError("%s: a move is in progress" % self.name)
        if not self._enabled:
            raise StepperUsageError(
                "%s is disabled -- 'enable both' first" % self.name)
        _clear_fifos(self.vel_sm_id)
        self.target_rate = 0
        self.current_rate = 0
        self._pos_micro = 0
        # Belt and braces with the pin-write bookkeeping in _apply_dir /
        # set_direction: on entry the cache is UNKNOWN, so the first non-zero
        # rate writes DIR from a standstill regardless of what any position
        # move, `invert`, or earlier velocity session left behind.
        self._vel_dir = 0
        self._claim_step_pin_vel()
        self.vel_sm.active(1)
        self._set_period(0)              # active but idle
        self.mode = "vel"

    def leave_vel_mode(self):
        if self.mode != "vel":
            return
        self._set_period(0)
        self.target_rate = 0
        self.current_rate = 0
        time.sleep_ms(2)
        self.vel_sm.active(0)
        self._release_step_pin()
        # Fold the dead-reckoned fraction back into the integer counter so
        # move-mode position picks up where velocity mode left off.
        self.position += self._pos_micro // 1000000
        self._pos_micro = 0          # phase deliberately survives: it tracks
                                     # the driver, not our datum
        self.mode = "idle"

    def _claim_step_pin_vel(self):
        funcsel = _FUNCSEL_PIO0 if self.vel_sm_id < 4 else _FUNCSEL_PIO1
        _set_funcsel(self.spec["step"], funcsel)

    def set_target_rate(self, rate):
        """Commanded signed rate in microsteps/s. Clamped, not rejected."""
        lim = config.VEL_MAX_RATE
        if rate > lim:
            rate = lim
        elif rate < -lim:
            rate = -lim
        self.target_rate = int(rate)

    def vel_tick(self, dt_us):
        """
        One control tick. Runs in interrupt context: MUST NOT ALLOCATE.

        Integer arithmetic throughout, because MicroPython heap-allocates
        floats on this port and the allocator is unavailable inside an ISR.
        Rates are microsteps/s as ints and position is accumulated in
        microsteps * 1e6 so a 5 ms tick at a few hundred steps/s still carries
        exactly, with no float and no drift.

        The first version of this used floats and `for ax in self.axes.values()`
        -- a dict view plus an iterator, 200 times a second. It ran the board
        out of heap inside the ISR, USB CDC stopped being serviced, and the
        console wedged hard enough to need a power cycle. The motors were safe
        (the watchdog had already zeroed them) but nothing else was.
        """
        tr = self.target_rate
        cr = self.current_rate
        if cr != tr:
            step = self._accel_per_tick
            d = tr - cr
            if d > step:
                cr += step
            elif d < -step:
                cr -= step
            else:
                cr = tr

        # DIR is latched on the step edge, so a reversal must happen at a
        # standstill or the step is lost silently.
        if cr > 0:
            want = 1
        elif cr < 0:
            want = -1
        else:
            want = self._vel_dir
        if want != self._vel_dir:
            self._set_period(0)
            time.sleep_us(300)
            self._apply_dir(want > 0)
            self._vel_dir = want

        self.current_rate = cr
        mag = cr if cr >= 0 else -cr
        if mag:
            period = self._vel_clock // mag
            y = period - config.VEL_CYCLE_OVERHEAD
            if y < 1:
                y = 1
        else:
            y = 0
        self._set_period(y)
        # micro-steps scaled by 1e6; dt_us is an int, so this stays integral.
        d = cr * dt_us
        self._pos_micro += d
        self._phase_micro += d * self._phase_mult

    @property
    def vel_position(self):
        """Dead-reckoned position while in velocity mode."""
        return self.position + self._pos_micro // 1000000

    @property
    def phase16(self):
        """Driver translator phase in 1/16-step units. Never re-zeroed."""
        return self._phase_micro // 1000000

    def _apply_dir(self, forward):
        """Direction pin only, no allocation -- safe from the timer ISR."""
        level = 1 if forward else 0
        if self._invert_dir:
            level ^= 1
        self.dir_pin.value(level)
        self._vel_dir = 1 if forward else -1      # small int: no allocation

    def set_direction(self, forward):
        level = 1 if forward else 0
        if config.INVERT_DIR.get(self.name, False):
            level ^= 1
        self.dir_pin.value(level)
        # Keep the velocity-mode cache honest: this is the write that used to
        # desynchronise it (see __init__ on _vel_dir).
        self._vel_dir = 1 if forward else -1
        # A4988 DIR setup time before a STEP rising edge is 200 ns; be generous.
        time.sleep_us(5)
        return level

    # ------------------------------------------------------------------
    # Units
    # ------------------------------------------------------------------
    def steps_per_rev(self):
        return (config.FULL_STEPS_PER_REV * self.microstep
                * config.GEAR_RATIO.get(self.name, 1.0))

    def degrees_to_steps(self, deg):
        return int(round(deg * self.steps_per_rev() / 360.0))

    def steps_to_degrees(self, steps):
        return steps * 360.0 / self.steps_per_rev()

    # ------------------------------------------------------------------
    # Motion
    # ------------------------------------------------------------------
    def abort(self):
        self._abort = True

    def _delay_word(self, rate):
        """Convert microsteps/sec into a PIO delay word."""
        rate = max(1.0, min(float(rate), config.ABSOLUTE_MAX_RATE))
        period_cycles = int(round(config.PIO_CLOCK_HZ / rate))
        word = period_cycles - _PIO_OVERHEAD_CYCLES
        if word < 0:
            word = 0
        return word

    def actual_rate(self, requested):
        """The rate you really get after PIO quantisation."""
        word = self._delay_word(requested)
        return config.PIO_CLOCK_HZ / float(word + _PIO_OVERHEAD_CYCLES)

    def move(self, steps, rate=None, accel=None, start_rate=None,
             on_progress=None, guard=None, gc_collect=None):
        """
        Move `steps` microsteps (sign = direction) with a trapezoidal ramp.

        guard      -- callable returning True to stop immediately (endstops).
        on_progress-- callable(done, total) invoked every ~64 steps.
        gc_collect -- None (default) collects only for moves of at least
                      _GC_THRESHOLD_STEPS.  Pass True/False to force it.
                      Timing measurements need this pinned, because a
                      collect that happens on one move and not another
                      adds ~1.7 ms of overhead to just one of them.

        Returns a dict describing what actually happened.
        """
        if steps == 0:
            return {"steps": 0, "aborted": False, "guarded": False,
                    "elapsed_us": 0}
        if not self._enabled:
            raise StepperError("%s is not enabled -- call enable() first"
                               % self.name)
        # Two step generators share one STEP pin. Letting a move start while
        # the velocity SM is driving it would have both writing the same pad,
        # and the result is not "both move" but a garbled pulse train that
        # loses steps without reporting anything.
        if self.mode == "vel":
            # USAGE, NOT A FAULT. cli.py answers a plain StepperError by
            # calling safe_state(), which de-energises BOTH axes -- and on a
            # tilt axis with gravity on it that drops the barrel. Asking for a
            # move at the wrong moment is a mistake to report, not a reason to
            # let go. Measured 2026-09-20: every refusal came back
            # "[everything disabled]" with the payload held at -37.7 deg.
            raise StepperUsageError(
                "%s is in velocity mode -- 'velmode off' before moving"
                % self.name)

        forward = steps > 0
        total = abs(int(steps))
        self.set_direction(forward)

        v_max = float(rate if rate is not None
                      else config.MAX_RATE.get(self.name, 2000))
        v_min = float(start_rate if start_rate is not None
                      else config.START_RATE.get(self.name, 200))
        a = float(accel if accel is not None
                  else config.ACCEL.get(self.name, 20000))

        v_max = max(1.0, min(v_max, config.ABSOLUTE_MAX_RATE))
        v_min = max(1.0, min(v_min, v_max))

        # Steps needed to reach v_max from v_min under constant accel:
        #   v^2 = v0^2 + 2*a*n  ->  n = (v_max^2 - v_min^2) / (2a)
        if a > 0:
            ramp_n = int((v_max * v_max - v_min * v_min) / (2.0 * a))
        else:
            ramp_n = 0
        ramp_n = max(0, ramp_n)

        # If the move is too short to reach v_max, use a triangular profile.
        if 2 * ramp_n > total:
            ramp_n = total // 2

        cruise_n = total - 2 * ramp_n

        self._abort = False
        sm = self.sm
        sm.active(0)
        _clear_fifos(self.sm_id)   # drop anything left by an aborted move
        sm.restart()
        self._claim_step_pin()
        sm.active(1)

        # The FIFO is only 4 deep; an underrun just stretches one step, which
        # is harmless, but a GC pause mid-ramp is ugly.  Collect up front --
        # only for moves long enough to be at risk, since gc.collect() costs
        # ~1.7 ms on this heap and would otherwise dominate short moves.
        if gc_collect is None:
            gc_collect = total >= _GC_THRESHOLD_STEPS
        if gc_collect:
            gc.collect()

        done = 0
        t0 = time.ticks_us()
        guarded = False
        try:
            # ---- accelerate ----
            v = v_min
            two_a = 2.0 * a
            vmin_sq = v_min * v_min
            for n in range(ramp_n):
                v = (vmin_sq + two_a * n) ** 0.5
                sm.put(self._delay_word(v))
                done += 1
                if (done & 63) == 0:
                    reason = self._check_stop(guard, on_progress, done, total)
                    if reason:
                        guarded = (reason == "guard")
                        raise _Stop()

            # ---- cruise ----
            word = self._delay_word(v_max if ramp_n else v_min)
            for _ in range(cruise_n):
                sm.put(word)
                done += 1
                if (done & 63) == 0:
                    reason = self._check_stop(guard, on_progress, done, total)
                    if reason:
                        guarded = (reason == "guard")
                        raise _Stop()

            # ---- decelerate ----
            for n in range(ramp_n):
                v = (vmin_sq + two_a * (ramp_n - 1 - n)) ** 0.5
                sm.put(self._delay_word(v))
                done += 1
                if (done & 63) == 0:
                    reason = self._check_stop(guard, on_progress, done, total)
                    if reason:
                        guarded = (reason == "guard")
                        raise _Stop()

            # Let the FIFO drain so `done` reflects pulses actually emitted.
            # With autopull on, the SM stalls at `out` once the FIFO is empty,
            # so this terminates cleanly.
            while sm.tx_fifo() > 0:
                if guard is not None and guard():
                    guarded = True
                    break
            # One word may still be in the OSR mid-execution.  Both profiles
            # finish at v_min -- a full ramp decelerates back down to it, and
            # an accel=0 move cruises at it -- so wait out that period rather
            # than a fixed guess, or the elapsed time comes out short at low
            # rates and the timing test reports a phantom error.
            tail_us = ((self._delay_word(v_min) + _PIO_OVERHEAD_CYCLES)
                       * 1000000 // config.PIO_CLOCK_HZ)
            time.sleep_us(min(tail_us + 50, 50000))

        except _Stop:
            pass
        finally:
            sm.active(0)
            # Read the FIFO depth BEFORE clearing it -- words still queued
            # were never turned into pulses.
            leftover = sm.tx_fifo()
            _clear_fifos(self.sm_id)
            self._release_step_pin()
            # Update position HERE, not after the try, so it stays correct
            # even when the move dies by exception -- a Ctrl-C e-stop raises
            # KeyboardInterrupt straight through this frame, and if the
            # position update sat below the try/finally it would be skipped,
            # silently desynchronising the axis from reality at exactly the
            # moment you most need to trust it.
            emitted = done - leftover
            self.position += emitted if forward else -emitted
            # Phase follows every real pulse, in either mode.
            self._phase_micro += ((emitted if forward else -emitted)
                                  * self._phase_mult * 1000000)

        elapsed = time.ticks_diff(time.ticks_us(), t0)

        result = {
            "steps": emitted if forward else -emitted,
            "requested": steps,
            "aborted": self._abort,
            "guarded": guarded,
            "elapsed_us": elapsed,
            "ramp_steps": ramp_n,
            "cruise_steps": cruise_n,
            "peak_rate": v_max if ramp_n else v_min,
            "position": self.position,
        }
        self._last_move = result
        if on_progress:
            on_progress(done, total)
        return result

    def _check_stop(self, guard, on_progress, done, total):
        """Return None to keep going, else 'abort' or 'guard'."""
        if on_progress:
            on_progress(done, total)
        if self._abort:
            return "abort"
        if guard is not None and guard():
            return "guard"
        return None

    def move_degrees(self, deg, **kw):
        return self.move(self.degrees_to_steps(deg), **kw)

    def single_step(self, forward=True, high_us=10, low_us=10000):
        """One bit-banged pulse.  For scoping and for slow visual checks."""
        if not self._enabled:
            raise StepperError("%s is not enabled" % self.name)
        if self.mode == "vel":
            raise StepperError(
                "%s is in velocity mode -- 'velmode off' first" % self.name)
        self._release_step_pin()       # make sure SIO owns the pad
        self.set_direction(forward)
        self.step_pin.value(1)
        time.sleep_us(high_us)
        self.step_pin.value(0)
        time.sleep_us(low_us)
        self.position += 1 if forward else -1
        self._phase_micro += ((1 if forward else -1)
                              * self._phase_mult * 1000000)
        return self.position

    def zero(self):
        self.position = 0

    def status(self):
        f = self.fault()
        return {
            "name": self.name,
            "ref": self.ref,
            "enabled": self._enabled,
            "microstep": self.microstep,
            "position": self.position,
            "degrees": round(self.steps_to_degrees(self.position), 3),
            "steps_per_rev": self.steps_per_rev(),
            "pad2_mode": self.pad2_mode,
            "fault": f,
            "dir_level": self.dir_pin.value(),
        }


class _Stop(Exception):
    pass


def _set_drive_strength(gpio, level):
    """PADS_BANK0 DRIVE field: 0=2mA 1=4mA 2=8mA 3=12mA."""
    try:
        PADS_BANK0 = 0x4001C000
        addr = PADS_BANK0 + 0x04 + 4 * gpio
        val = machine.mem32[addr]
        val = (val & ~(0x3 << 4)) | ((level & 0x3) << 4)
        machine.mem32[addr] = val
        return True
    except Exception:
        return False


# --------------------------------------------------------------------------
# Direct RP2040 register pokes.  MicroPython's rp2 module does not expose
# either of these operations, and both are needed for correct behaviour:
#   * FUNCSEL, so the STEP pad can be handed between PIO and SIO
#   * FIFO clear, so an aborted move does not leak queued steps into the next
# --------------------------------------------------------------------------
_IO_BANK0 = 0x40014000
_FUNCSEL_SIO = 5
_FUNCSEL_PIO0 = 6
_FUNCSEL_PIO1 = 7

_PIO_BASE = (0x50200000, 0x50300000)
_SM0_SHIFTCTRL = 0x0D0
_SM_STRIDE = 0x18
_FJOIN_RX_BIT = 1 << 31


def _set_funcsel(gpio, funcsel):
    try:
        addr = _IO_BANK0 + 0x04 + 8 * gpio        # GPIOn_CTRL
        val = machine.mem32[addr]
        machine.mem32[addr] = (val & ~0x1F) | (funcsel & 0x1F)
        return True
    except Exception:
        return False


def _get_funcsel(gpio):
    """Read a pad's current function select. None if it cannot be read.

    5 == SIO, 6 == PIO0, 7 == PIO1 (the constants above). This exists so the
    `pads` diagnostic can answer, in one command, "is the velocity state
    machine actually connected to the STEP pin?" -- the question that cost an
    evening when an axis counted steps it was not emitting.
    """
    try:
        return machine.mem32[_IO_BANK0 + 0x04 + 8 * gpio] & 0x1F
    except Exception:
        return None


def _clear_fifos(sm_id):
    """Equivalent of the SDK's pio_sm_clear_fifos(): toggle FJOIN_RX twice."""
    try:
        base = _PIO_BASE[0 if sm_id < 4 else 1]
        addr = base + _SM0_SHIFTCTRL + (sm_id % 4) * _SM_STRIDE
        machine.mem32[addr] = machine.mem32[addr] ^ _FJOIN_RX_BIT
        machine.mem32[addr] = machine.mem32[addr] ^ _FJOIN_RX_BIT
        return True
    except Exception:
        return False


# --------------------------------------------------------------------------
# Coordinated two-motor motion, for the differential
# --------------------------------------------------------------------------


def _profile_time_fn(n, v_max, v_min, a):
    """
    Build t(s): the time at which the profile reaches step position `s`.

    Returns a closure over a trapezoidal profile spanning `n` steps. Working
    in *time* rather than per-step rates is what lets two motors share one
    timeline exactly -- scaling two rate profiles independently makes their
    ramp step-counts round differently, and they then finish a few percent
    apart, which shows up as a dogleg at the end of a combined move.
    """
    v_max = max(1e-6, v_max)
    v_min = max(1e-6, min(v_min, v_max))
    if a > 0:
        ramp = int((v_max * v_max - v_min * v_min) / (2.0 * a))
    else:
        ramp = 0
    ramp = max(0, ramp)
    if 2 * ramp > n:
        ramp = n // 2
    cruise = n - 2 * ramp
    vmin_sq = v_min * v_min

    if ramp:
        v_peak = (vmin_sq + 2.0 * a * ramp) ** 0.5
        t_ramp = (v_peak - v_min) / a
    else:
        v_peak = v_min
        t_ramp = 0.0
    t_cruise_end = t_ramp + cruise / v_peak
    t_total = t_cruise_end + t_ramp

    def t_at(s):
        if s <= 0.0:
            return 0.0
        if s >= n:
            return t_total
        if ramp and s <= ramp:
            return ((vmin_sq + 2.0 * a * s) ** 0.5 - v_min) / a
        if s <= ramp + cruise:
            return t_ramp + (s - ramp) / v_peak
        d = n - s                      # steps still to go, mirror of the ramp
        return t_total - ((vmin_sq + 2.0 * a * d) ** 0.5 - v_min) / a

    return t_at


def _sync_delays(n_self, n_dom, t_at):
    """
    Yield the gap in seconds between consecutive steps for one motor.

    `t_at` is the shared timeline defined over `n_dom` dominant-axis steps.
    A motor taking `n_self` steps places its j-th step at path fraction
    j/n_self, i.e. at dominant position j*n_dom/n_self. Both motors read the
    same clock, so they cannot drift apart.
    """
    if n_self <= 0:
        return
    scale = float(n_dom) / n_self
    prev = 0.0
    for j in range(1, n_self + 1):
        t = t_at(j * scale)
        dt = t - prev
        prev = t
        yield dt if dt > 1e-9 else 1e-9


def coordinated_move(axis_a, axis_b, steps_a, steps_b, rate=None, accel=None,
                     start_rate=None, guard=None, on_progress=None):
    """
    Move both motors at once, starting and finishing together.

    This is what the differential needs. Running one axis and then the other
    would trace an L-shaped path through (pitch, yaw) -- the payload would
    swing out and come back instead of going straight there. Both motors are
    fed from a single loop, and the shorter move's profile is time-scaled so
    the two finish on the same tick.

    `rate` / `start_rate` / `accel` apply to the DOMINANT motor (the one with
    more steps); the other is scaled down in proportion.
    """
    if not (axis_a.enabled and axis_b.enabled):
        raise StepperError("both motors must be enabled for a coordinated move")

    # THE GUARD move() AND single_step() BOTH HAVE AND THIS DID NOT.
    #
    # Two step generators share one STEP pin per axis. Running a coordinated
    # move while an axis is in velocity mode has both writing the same pad,
    # and -- worse -- the finally clause below calls _release_step_pin() on
    # both axes, handing the pad to SIO while the velocity SM is still
    # active and still being fed periods. The axis then counts steps it
    # never emits until the next reboot.
    for ax in (axis_a, axis_b):
        if ax.mode == "vel":
            # StepperUsageError, not StepperError -- see the same guard in
            # Axis.move(). A refused move must not de-energise a loaded axis.
            raise StepperUsageError(
                "%s is in velocity mode -- 'velmode off' before moving"
                % ax.name)

    na, nb = int(steps_a), int(steps_b)
    fwd_a, fwd_b = na > 0, nb > 0
    aa, ab = abs(na), abs(nb)
    n_max = max(aa, ab)

    if n_max == 0:
        return {"steps_a": 0, "steps_b": 0, "aborted": False,
                "guarded": False, "elapsed_us": 0, "requested": (na, nb)}

    v_max = float(rate if rate is not None
                  else config.MAX_RATE.get(axis_a.name, 2000))
    v_min = float(start_rate if start_rate is not None
                  else config.START_RATE.get(axis_a.name, 200))
    acc = float(accel if accel is not None
                else config.ACCEL.get(axis_a.name, 20000))
    v_max = max(1.0, min(v_max, config.ABSOLUTE_MAX_RATE))
    v_min = max(1.0, min(v_min, v_max))

    # One timeline, defined over the dominant axis; both motors sample it.
    t_at = _profile_time_fn(n_max, v_max, v_min, acc)
    gen_a = _sync_delays(aa, n_max, t_at)
    gen_b = _sync_delays(ab, n_max, t_at)

    axis_a.set_direction(fwd_a)
    axis_b.set_direction(fwd_b)
    axis_a._abort = False
    axis_b._abort = False

    for ax in (axis_a, axis_b):
        ax.sm.active(0)
        _clear_fifos(ax.sm_id)
        ax.sm.restart()
        ax._claim_step_pin()
        ax.sm.active(1)

    if n_max >= _GC_THRESHOLD_STEPS:
        gc.collect()

    done_a = done_b = 0
    fed_a = fed_b = False if aa or ab else True
    end_a = aa == 0
    end_b = ab == 0
    guarded = False
    t0 = time.ticks_us()

    try:
        while not (end_a and end_b):
            moved = False
            if not end_a and axis_a.sm.tx_fifo() < 4:
                try:
                    axis_a.sm.put(axis_a._delay_word(1.0 / next(gen_a)))
                    done_a += 1
                    moved = True
                except StopIteration:
                    end_a = True
            if not end_b and axis_b.sm.tx_fifo() < 4:
                try:
                    axis_b.sm.put(axis_b._delay_word(1.0 / next(gen_b)))
                    done_b += 1
                    moved = True
                except StopIteration:
                    end_b = True

            if ((done_a + done_b) & 63) == 0 or not moved:
                if on_progress:
                    on_progress(done_a + done_b, aa + ab)
                if axis_a._abort or axis_b._abort:
                    raise _Stop()
                if guard is not None and guard():
                    guarded = True
                    raise _Stop()

        while axis_a.sm.tx_fifo() > 0 or axis_b.sm.tx_fifo() > 0:
            if guard is not None and guard():
                guarded = True
                break
        tail = ((axis_a._delay_word(v_min) + _PIO_OVERHEAD_CYCLES)
                * 1000000 // config.PIO_CLOCK_HZ)
        time.sleep_us(min(tail + 50, 50000))

    except _Stop:
        pass
    finally:
        left_a = left_b = 0
        for ax in (axis_a, axis_b):
            ax.sm.active(0)
        left_a = axis_a.sm.tx_fifo()
        left_b = axis_b.sm.tx_fifo()
        for ax in (axis_a, axis_b):
            _clear_fifos(ax.sm_id)
            ax._release_step_pin()
        emit_a = done_a - left_a
        emit_b = done_b - left_b
        axis_a.position += emit_a if fwd_a else -emit_a
        axis_b.position += emit_b if fwd_b else -emit_b

    return {
        "steps_a": emit_a if fwd_a else -emit_a,
        "steps_b": emit_b if fwd_b else -emit_b,
        "requested": (na, nb),
        "aborted": axis_a._abort or axis_b._abort,
        "guarded": guarded,
        "elapsed_us": time.ticks_diff(time.ticks_us(), t0),
        "peak_rate": v_max,
    }


# --------------------------------------------------------------------------
# Factory
# --------------------------------------------------------------------------
class VelocityLoop:
    """
    The 200 Hz loop that makes velocity mode a mode rather than a command.

    Everything here exists because a tracking turret must never stop. The host
    sends a RATE, this holds it, and motion is continuous between commands --
    as opposed to `aim`, which accelerates from rest, arrives, and decelerates
    to a standstill every single time. Measured on this hardware, a 4.7 deg
    `aim` costs 164-325 ms of which ~139 ms is the ramp up and back down, so
    commanding position at frame rate yields a few discrete hops per second.
    That is the "jumping to where the mouse is" failure exactly.

    THE WATCHDOG IS NOT OPTIONAL. In move mode a lost USB link means a move
    finishes and the motors stop. In velocity mode it means a motor holds its
    last rate forever. So a tick with no recent `vel` ramps the target to zero
    and cuts the laser by direct GPIO write -- not through the CLI, which may
    be exactly what is wedged.
    """

    def __init__(self, axes, laser_pin=None):
        self.axes = axes
        # Bound to plain attributes because the ISR must not iterate: a dict
        # view and its iterator are two allocations per tick, and the ISR has
        # no allocator. Two motors, two attributes, no loop.
        self._a = axes["pan"]
        self._b = axes["tilt"]
        self.laser_pin = laser_pin
        self.timer = None
        self._dt_us = config.VEL_TICK_MS * 1000
        self._last_cmd_ms = 0
        self._tripped = False
        self.ticks = 0
        self.trips = 0
        self._limited = False
        self._pitch_sum_limit = 0
        # --- IMU crash guard, published from ordinary context -------------
        # PLAIN BOOLEANS, and they must stay that way. The ISR reads these;
        # it cannot call into guard.py, because a decision needs an I2C
        # transaction and an I2C transaction allocates and can raise. So the
        # measuring happens on the command path (see apply_guard) and the ISR
        # does nothing but compare a sign and zero a rate.
        self._blk_pos = False      # refuse a pitch push > 0
        self._blk_neg = False      # refuse a pitch push < 0
        self._blk_all = False      # impact latched: refuse everything
        self._guard_stops = 0
        self._guard_hit = False
        #: Step-sum reading at the last start(), so the pitch clamp's frame is
        #: centred on the pose tracking STARTED from rather than on whatever
        #: `position` homing happened to leave behind. See start().
        self._tot0 = 0
        self.shifts = 0
        self._shift_pending = 0
        self._shift_deferred_out = 0
        self._gear_request = 16
        self._gear_request_ms = 0
        self._last_shift_ms = -500
        self.gear_capped = False

    # ------------------------------------------------------------------
    def start(self):
        if self.timer is not None:
            return
        self._a.enter_vel_mode()
        self._b.enter_vel_mode()
        self._last_cmd_ms = time.ticks_ms()
        self._tripped = False
        # `limited` is a latch so a host that polls slowly still sees that the
        # clamp fired. Clear it HERE so it means "during this tracking run"
        # rather than "at some point since the board booted" -- otherwise the
        # first run that clamps makes every later run report limited.
        self._limited = False
        # The crash guard's LATCH is likewise per-run, for the same reason:
        # it is evidence about this run. The block flags themselves are NOT
        # cleared here -- they are a live measurement of where the payload is
        # right now, and starting velocity mode does not move it. Clearing
        # them would hand back a full-speed gate to a payload sitting against
        # its frame.
        self._guard_hit = False
        # CENTRE THE CLAMP ON THE POSE WE ARE STARTING FROM.
        #
        # _arm_pitch_limit's docstring says the frame is centred on the placed
        # pose, but _tick compared the RAW sum, and vel_position is
        # `position + _pos_micro // 1e6` -- `position` being the position-mode
        # counter left over from homing, which enter_vel_mode does not reset
        # (it resets only _pos_micro). Taking the reading here makes the frame
        # mean what it claims.
        # Fixed 1/16 units: a gear change must not move the travel-limit datum.
        self._tot0 = ((self._a.vel_position + self._b.vel_position) * 16
                      // self._a.microstep)
        self._gear_request = self._a.microstep
        self._gear_request_ms = time.ticks_ms()
        self._last_shift_ms = time.ticks_ms() - 500
        self._arm_pitch_limit()
        self.timer = Timer()
        self.timer.init(period=config.VEL_TICK_MS,
                        mode=Timer.PERIODIC, callback=self._tick)

    def _arm_pitch_limit(self):
        """
        Precompute the pitch travel limit as an integer step sum.

        `vel` and `pvel` are RATE commands, so nothing in the move path's
        limit checking applies to them -- the firmware would happily drive the
        payload through the yoke at a steady 400 steps/s. The limit has to be
        enforced here, in the only code that sees every tick.

        For a differential, pitch is proportional to the SUM of the two motor
        positions (and yaw to their difference), so the whole check reduces to
        one integer comparison against a precomputed bound. Computed once per
        start() because it depends on microstepping.
        """
        lim = config.PAYLOAD_LIMIT_DEG.get("pitch")
        if not lim:
            self._pitch_sum_limit = 0          # 0 == no limit
            return
        ms = 16  # travel-limit comparison and datum stay in canonical units
        motor_step_deg = 360.0 / (config.FULL_STEPS_PER_REV * ms)
        bound = max(abs(lim[0]), abs(lim[1]))
        self._pitch_sum_limit = int(
            bound * 2.0 * config.DIFFERENTIAL_N / motor_step_deg)

    def stop(self):
        if self.timer is not None:
            self.timer.deinit()
            self.timer = None
        dynamic = getattr(config, "VEL_CANONICAL16", False)
        if dynamic:
            # Preserve sub-coarse-step fractions before leave_vel_mode folds
            # them into an integer. Otherwise stopping in 1/8 loses fine steps.
            pa16 = ((self._a.position * 1000000 + self._a._pos_micro) * 16
                    // self._a.microstep // 1000000)
            pb16 = ((self._b.position * 1000000 + self._b._pos_micro) * 16
                    // self._b.microstep // 1000000)
        self._a.leave_vel_mode()
        self._b.leave_vel_mode()
        if dynamic:
            # Position commands, homing and the end-of-run rewind use fine
            # units. Returning to finer steps needs no phase alignment.
            self._a.set_microstep(16)
            self._b.set_microstep(16)
            self._a.position, self._b.position = pa16, pb16
            self._arm_pitch_limit()

    @property
    def running(self):
        return self.timer is not None

    # ------------------------------------------------------------------
    def command(self, rate_a, rate_b):
        """Set both motor rates and pet the watchdog."""
        if not self.running:
            self.start()
        # Shift first, then convert the request into the units the shift just
        # created. A rate arrives expressed in the CURRENT microstep, and a
        # shift changes what a step is worth -- applying an old-units rate
        # after a 16->4 shift commands four times the intended speed. The
        # first version of this did exactly that and drove straight through
        # the travel limit.
        before = self._a.microstep
        self._maybe_shift(rate_a, rate_b)
        after = self._a.microstep
        if after != before:
            rate_a = rate_a * after / before
            rate_b = rate_b * after / before
        self.gear_capped = False
        if getattr(config, "VEL_CANONICAL16", False):
            peak = max(abs(rate_a), abs(rate_b))
            limit = config.VEL_DYNAMIC_PULSE_LIMIT
            if peak > limit:
                factor = limit / peak
                rate_a *= factor
                rate_b *= factor
                self.gear_capped = True
        self._a.set_target_rate(rate_a)
        self._b.set_target_rate(rate_b)
        self._last_cmd_ms = time.ticks_ms()
        self._tripped = False

    # ------------------------------------------------------------------
    def _gear_for(self, payload_dps):
        """Divisor for a payload speed, with hysteresis about the current one."""
        cur = self._a.microstep
        h = config.VEL_GEAR_HYSTERESIS
        pick = config.VEL_GEARS[-1][1]
        for thresh, div in config.VEL_GEARS:
            # Widen the band we are already in, so speeds hovering on a
            # boundary do not shift back and forth every command.
            t = thresh * (1.0 + h) if div == cur else thresh
            if payload_dps <= t:
                pick = div
                break
        return pick

    def _maybe_shift(self, rate_a, rate_b):
        """
        Change microstepping to suit the commanded speed.

        Called from the command path, never the ISR: a shift means touching
        three GPIOs per driver, a settle delay and a rescale of both step
        counters, none of which belongs in an interrupt.
        """
        if not getattr(config, "VEL_GEARSHIFT", False):
            return
        if getattr(config, "VEL_CANONICAL16", False):
            self._maybe_shift_dynamic(rate_a, rate_b)
            return
        cur = self._a.microstep
        if self._b.microstep != cur:
            return                     # mismatched; kinematics will complain
        # Payload speed from the two motor rates: pitch and yaw are the sum
        # and difference, and the faster of the two is what has to be served.
        deg_per_step = 360.0 / (config.FULL_STEPS_PER_REV * cur
                                * config.DIFFERENTIAL_N)
        pitch_dps = abs(rate_a + rate_b) * deg_per_step / 2.0
        yaw_dps = abs(rate_a - rate_b) * deg_per_step / 2.0
        want = self._gear_for(pitch_dps if pitch_dps > yaw_dps else yaw_dps)
        if want == cur:
            self._shift_pending = 0
            return

        # Only shift where the counts line up exactly.
        #
        # An A4988 jumps its internal indexer to the nearest state in the new
        # table when MSx changes, so shifting off an unaligned count moves the
        # motor by up to one fine step -- physically, silently, and with
        # nothing to detect it because this platform has no encoder. Landing
        # on a count that is valid in BOTH tables makes the shift exact.
        # Coarse->fine is always safe: every coarse translator state is also a
        # valid fine state, so no alignment is needed in that direction.
        if cur > want:
            ratio16 = 16 // want
            if (self._a.phase16 % ratio16) or (self._b.phase16 % ratio16):
                # Unaligned. If nothing is turning the phase will never
                # advance, so waiting is pointless and forcing would cost a
                # step for no gain -- just stay in the finer gear.
                if self._a.current_rate == 0 and self._b.current_rate == 0:
                    return
                # Not aligned yet. It will be within a few steps; defer.
                # Alignment comes round every `ratio16` sixteenth-steps, so
                # at any real rate this resolves within milliseconds. The
                # counter only exists so a pathological case cannot wedge the
                # gear forever.
                self._shift_pending += 1
                if self._shift_pending < 60:
                    return
                self._shift_deferred_out += 1
        self._shift_pending = 0
        self._do_shift(want)

    def _maybe_shift_dynamic(self, rate_a, rate_b):
        """Two gears, separated thresholds and dwell; never force alignment."""
        cur = self._a.microstep
        if cur != self._b.microstep or cur not in (8, 16):
            raise StepperUsageError("dynamic profile requires paired 1/8 or 1/16")
        demand16 = max(abs(rate_a), abs(rate_b)) * 16 / cur
        actual16 = max(abs(self._a.current_rate), abs(self._b.current_rate)) * 16 / cur
        fine_cap = config.VEL_DYNAMIC_PULSE_LIMIT
        want = cur
        if cur == 16 and demand16 > .70 * fine_cap:
            want = 8
        elif cur == 8 and max(demand16, actual16) < .40 * fine_cap:
            want = 16
        now = time.ticks_ms()
        if want != self._gear_request:
            self._gear_request = want
            self._gear_request_ms = now
        if want == cur or time.ticks_diff(now, self._last_shift_ms) < 500:
            return
        dwell = 100 if want == 8 else 300
        if time.ticks_diff(now, self._gear_request_ms) < dwell:
            return
        if want == 8 and (self._a.phase16 % 2 or self._b.phase16 % 2):
            self._shift_deferred_out += 1
            return
        if self._do_shift(want):
            self._last_shift_ms = now

    def _do_shift(self, div):
        """Exclude the ISR while changing paired units and driver pins.

        phase16 is the existing dead-reckoned phase, NOT a hardware pulse
        counter. Physical phase continuity must still be checked on the rig.
        """
        a, b = self._a, self._b
        irq = machine.disable_irq()
        try:
            old = a.microstep
            if div < old and (a.phase16 % (16 // div) or b.phase16 % (16 // div)):
                return False
            a.vel_sm.active(0)
            b.vel_sm.active(0)
            # Let any high pulse meet the driver minimum before parking low.
            time.sleep_us(5)
            a.vel_sm.exec(_VEL_SET_LOW)
            b.vel_sm.exec(_VEL_SET_LOW)
            a._set_period(0)
            b._set_period(0)
            for ax in (a, b):
                total = (ax.position * 1000000 + ax._pos_micro) * div // old
                ax.set_microstep(div)
                # Do not independently truncate the base and accumulated
                # fraction: repeated 16->8->16 shifts would walk the datum.
                ax.position = total // 1000000
                ax._pos_micro = total - ax.position * 1000000
                ax._set_period(ax._period_for(abs(ax.current_rate)))
            self._arm_pitch_limit()
            a.vel_sm.active(1)
            b.vel_sm.active(1)
            self.shifts += 1
            return True
        except Exception:
            # Leave both generators parked if only part of a shift succeeded.
            a.vel_sm.active(0)
            b.vel_sm.active(0)
            a.target_rate = b.target_rate = 0
            a.current_rate = b.current_rate = 0
            if self.laser_pin is not None:
                self.laser_pin.value(0)
            raise
        finally:
            machine.enable_irq(irq)

    def apply_guard(self, guard):
        """Publish a CrashGuard's decision to the ISR. ORDINARY CONTEXT ONLY.

        Called from the `vel`/`pvel` command path immediately after the guard
        has sampled, so the flags the ISR sees are never more than one host
        command old. Copying them onto plain attributes here -- rather than
        letting the ISR reach into the guard object -- keeps the interrupt
        free of attribute chains on an object that may be None, mid-update, or
        holding a half-written float.
        """
        if guard is None:
            self._blk_pos = self._blk_neg = self._blk_all = False
            return
        self._blk_pos = bool(guard.block_pos)
        self._blk_neg = bool(guard.block_neg)
        self._blk_all = bool(guard.impact)

    def age_ms(self):
        return time.ticks_diff(time.ticks_ms(), self._last_cmd_ms)

    @property
    def tripped(self):
        return self._tripped

    @property
    def limited(self):
        return self._limited

    @property
    def guard_hit(self):
        """True if the IMU crash guard stopped the payload during this run."""
        return self._guard_hit

    @property
    def guard_stops(self):
        return self._guard_stops

    # ------------------------------------------------------------------
    def _tick(self, _t):
        # INTERRUPT CONTEXT. No allocation, no iteration, no formatting, and
        # nothing that can raise -- an exception here leaves a motor running.
        self.ticks += 1
        if time.ticks_diff(time.ticks_ms(),
                           self._last_cmd_ms) > config.VEL_WATCHDOG_MS:
            if not self._tripped:
                self._tripped = True
                self.trips += 1
                if self.laser_pin is not None:
                    self.laser_pin.value(0)
            self._a.target_rate = 0
            self._b.target_rate = 0
        # Pitch travel limit. Pitch is the SUM of the motor positions, yaw the
        # difference, so when the sum is at its bound the fix is to strip the
        # pitch component out of the command and keep the yaw component --
        # the payload stops tilting but can still turn, and can always move
        # back off the stop.
        lim = self._pitch_sum_limit
        if lim:
            tot = ((self._a.vel_position + self._b.vel_position) * 16
                   // self._a.microstep) - self._tot0
            if tot > lim or tot < -lim:
                ta = self._a.target_rate
                tb = self._b.target_rate
                push = ta + tb
                if (tot > 0 and push > 0) or (tot < 0 and push < 0):
                    # STOP, do not steer.
                    #
                    # This used to keep (ta - tb) // 2 and call it "the yaw
                    # component". When the demand is nearly PURE PITCH that
                    # residual is noise, and executing it is a yaw slew
                    # nobody asked for. Measured on run_2026-09-20_132627:
                    # the loop asked for (-319, -514) and the clamp executed
                    # (+97, -97) -- 4.75 deg/s of yaw -- which moved the
                    # drone's box 270 px AWAY from the goal and took the
                    # pixel error from 145 to 360. It reads exactly like a
                    # motor running backwards, and it is not.
                    #
                    # Zeroing both is the only response that cannot move the
                    # payload in a direction the control law never asked
                    # for. Coming back off the stop still works: the next
                    # command whose push has the opposite sign fails the
                    # test above and passes through untouched.
                    self._a.target_rate = 0
                    self._b.target_rate = 0
                    self._limited = True

        # IMU CRASH GUARD. The clamp above is dead reckoning: it counts steps
        # and believes them, which is exactly what stops being true when the
        # payload hits something. This one is the same shape of check against
        # a number that came from gravity -- see guard.py.
        #
        # Same response as the clamp, and for the same reason: ZERO BOTH, do
        # not steer. Keeping a "yaw component" of a refused pitch demand is
        # what drove the drone's box 270 px the wrong way on run_132627.
        if self._blk_all:
            self._a.target_rate = 0
            self._b.target_rate = 0
            if not self._guard_hit:
                self._guard_hit = True
                self._guard_stops += 1
            if self.laser_pin is not None:
                self.laser_pin.value(0)
        elif self._blk_pos or self._blk_neg:
            push = self._a.target_rate + self._b.target_rate
            if (push > 0 and self._blk_pos) or (push < 0 and self._blk_neg):
                self._a.target_rate = 0
                self._b.target_rate = 0
                if not self._guard_hit:
                    self._guard_hit = True
                    self._guard_stops += 1
        dt = self._dt_us
        self._a.vel_tick(dt)
        self._b.vel_tick(dt)


def build_axes():
    """Create both axes.  Pan uses PIO0 sm0, tilt uses PIO1 sm0."""
    return {
        "pan": Axis(pinmap.PAN, 0),
        "tilt": Axis(pinmap.TILT, 4),
    }
